### ISSUE TITLE
Action fails after Deployment complete!

### ISSUE THREAD

**Issue by vordimous** [cloudflare/pages-action#108]
cloudflare deploy succeeded but the action faild.

```
Run cloudflare/pages-action@v1
npm WARN exec The following package was not found and will be installed: wrangler@2.20.1
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
Uploading... (191/747)
Uploading... (377/747)
Uploading... (562/747)
Uploading... (747/747)
✨ Success! Uploaded 556 files (191 already uploaded) (4.91 sec)

✨ Uploading _redirects
✨ Deployment complete! Take a peek over at https://dec6eacb.***.pages.dev
npm notice 
npm notice New major version of npm available! 9.8.1 -> 10.2.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.1>
npm notice Run `npm install -g npm@10.2.1` to update!
npm notice 
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (/home/runner/work/_actions/cloudflare/pages-action/v1/index.js:13368:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createPagesDeployment (/home/runner/work/_actions/cloudflare/pages-action/v1/index.js:22105:9)
    at async /home/runner/work/_actions/cloudflare/pages-action/v1/index.js:22[17](https://github.com/***/actions/runs/6642497573/job/18047653004#step:4:18)5:[29](https://github.com/***/actions/runs/6642497573/job/18047653004#step:4:30)
```

**Comment by jharris-tc** [comment]
I am having exactly the same error

**Comment by WalshyDev** [comment]
There was an incident impacting multiple APIs - https://www.cloudflarestatus.com/incidents/s1hkh315y9s9
